source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', platform: :mri
gem 'activerecord-jdbcsqlite3-adapter', platform: :jruby
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

gem 'sidekiq', '~> 3.0'
gem 'sidekiq-hierarchy', '~> 0.0.dev', path: '../'
gem 'sinatra', require: nil
gem 'faraday', '~> 0.9'

group :development, :test do
  gem 'byebug', platform: :mri
end
